// little thesau
const byte anzBeis = 5;
const static char beis [anzBeis][128] __attribute__ (( aligned(SPM_PAGESIZE) )) PROGMEM = {
  "aalenabbauabendabgasabortabrufabteiabzugachimachseackeradelnadleradolfaehreaffigaffinafteragentagileahlenahmenahnenahninaktie",
  "eigeneileneiligeimereineneinereinigeiseneisigeiteleitereitleekelnekligekzemelendeliteelmaremsigendenengelengenenkelenormenzym",
  "appelaprilarchearealarenaarierarmeearminarndtarrakarschartenartigascheasiatasienasselathenatlasatmenaurumautoraxiombabelbacke",
  "badenbahrebaierbakerbambibanalbandebardebarkebaronbarrebasarbaselbasisbauchbauenbauerbayerbazarbeatebebenbeerebeetebeidebeize",
  "belagbelegbennoberndbertiberufbesenbetenbeterbetonbeugebeulebeutebezugbibelbiberbiegebienebiestbindebinombinsebirkebirnebison",
};
